// <auto-generated />
using System;
using Lararium.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lararium.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625193443_ConfigureEntities")]
    partial class ConfigureEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lararium.Core.LarariumUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("login");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middle_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Lararium.Media.Module.Actor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("birthday");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<Guid?>("VideoEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_entity_id");

                    b.HasKey("Id")
                        .HasName("pk_actors");

                    b.HasIndex("VideoEntityId")
                        .HasDatabaseName("ix_actors_video_entity_id");

                    b.ToTable("media_actors", (string)null);
                });

            modelBuilder.Entity("Lararium.Media.Module.MediaTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("VideoEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("video_entity_id");

                    b.HasKey("Id")
                        .HasName("pk_media_tags");

                    b.HasIndex("VideoEntityId")
                        .HasDatabaseName("ix_media_tags_video_entity_id");

                    b.ToTable("media_tags", (string)null);
                });

            modelBuilder.Entity("Lararium.Video.Models.VideoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FileExt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("file_ext");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint")
                        .HasColumnName("file_size");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("file_type");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_videos");

                    b.ToTable("videos", (string)null);
                });

            modelBuilder.Entity("Lararium.Media.Module.Actor", b =>
                {
                    b.HasOne("Lararium.Video.Models.VideoEntity", null)
                        .WithMany("Actors")
                        .HasForeignKey("VideoEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_actors_videos_video_entity_id");
                });

            modelBuilder.Entity("Lararium.Media.Module.MediaTag", b =>
                {
                    b.HasOne("Lararium.Video.Models.VideoEntity", null)
                        .WithMany("Tags")
                        .HasForeignKey("VideoEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_media_tags_videos_video_entity_id");
                });

            modelBuilder.Entity("Lararium.Video.Models.VideoEntity", b =>
                {
                    b.Navigation("Actors");

                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
