<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Abstractions" />
    <PackageReference Include="FFMpegCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lalarium.Core\Lararium.Core.csproj" />
    <ProjectReference Include="..\Lararium.Media\Lararium.Media.csproj" />
  </ItemGroup>

</Project>